---
# Detailed explanation of how this works is in https://projects.engineering.redhat.com/browse/RHV-2867
# Basically I'm creating a dict that holds a hosts group name as a key, and list of luns which were created for it.

- name: Create LUN mapping '{{ luns_iter.name }}'
  na_ontap_lun_map:
    state: present
    initiator_group_name: "{{ luns_iter.igroup }}"
    path:  "/vol/{{ luns_iter.name }}_vol/{{ luns_iter.name }}"
    vserver: "{{ luns_iter.vserver }}"
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
  register: create_lun_map_result_reg

- set_fact:
    create_lun_map_result: "{{ create_lun_map_result_reg }}"

- include: '{{role_path}}/tasks/create_record_of_luns_mapping.yml'
  when: ('create_record_of_luns_mapping' in actions)
  delegate_to: localhost