---

- name: check if nmon file already exist
  stat:
    path: "{{ nmon_local_dir }}/{{ nmon_tar }}"
  register: nmon_file_exist

- name: Download and extract nmon into local directory "{{ nmon_local_dir }}"
  block:
    - name: Create nmon local directory "{{ nmon_local_dir }}" 
      file: 
        state: directory
        path: "{{ nmon_local_dir }}"

    - name: Download nmon
      get_url: 
        url: "{{ nmon_url }}/{{ nmon_tar }}"
        dest: "{{ nmon_local_dir }}"

    - name: Extract nmon into {{ nmon_local_dir }}
      unarchive:
        src: "{{ nmon_local_dir }}/{{ nmon_tar }}"
        dest: "{{ nmon_local_dir }}"
  when: nmon_file_exist.stat.exists == false

# Install Nmon on CFME
- name: Copy nmon to CFME machine
  delegate_to: "{{ miq_vm_name }}.{{ miq_vm_dns_domain }}"
  copy:
    src: "{{ nmon_local_dir }}/{{ nmon_file }}"
    dest: "{{ nmon_location }}"
    mode: "0777"

# Add RHEL 8.1 repo and install Nmon requirements
- name: Gathering facts
  delegate_to: "{{ miq_vm_name }}.{{ miq_vm_dns_domain }}"
  setup:
- block:
    - name: Ensure wget package is installed on CFME
      delegate_to: "{{ miq_vm_name }}.{{ miq_vm_dns_domain }}"
      yum:
        name: wget
        state: present

    - name: check if /etc/yum.repos.d/rhel_81_x86.repo file already exist
      delegate_to: "{{ miq_vm_name }}.{{ miq_vm_dns_domain }}"
      stat:
        path: /etc/yum.repos.d/rhel_81_x86.repo
      register: repo_file_exist

    - name: Download rhel_81_x86.repo file to CFME RHEL 8 based
      delegate_to: "{{ miq_vm_name }}.{{ miq_vm_dns_domain }}"
      command: wget --no-check-certificate \
        https://code.engineering.redhat.com/gerrit/gitweb\?p\=rhevm-qe-automation/ansible-playbooks.git\;a\=blob_plain\;f\=roles/ci-map/files/rhel_81_x86.repo\;h\=4c95d8d16ab6979fbd507f005d66508bc5b85ee6\;hb\=refs/heads/master \
        -O /etc/yum.repos.d/rhel_81_x86.repo
      args:
        warn: no
      when: repo_file_exist.stat.exists == false

    - name: Install ncurses packages for RHEL 8 in order to run Nmon
      delegate_to: "{{ miq_vm_name }}.{{ miq_vm_dns_domain }}"
      command: "{{ command_item }}"
      with_items:
        - 'yum clean all'
        - 'sudo yum install -y libncurses*'
      loop_control:
        loop_var: command_item
      args:
        warn: no
  when: ansible_distribution_version == '8.1'

# Install Nmon on RHV hosts and conversion VMs
- include_tasks: rhv_install_nmon.yml
  with_items:
    - "{{ groups['ovirt_conversion_hosts'] }}"
    - "{{ groups['ovirt_conversion_host_vms'] }}"
  loop_control:
    loop_var: rhv_item
