---
- block:
    - name: Collect the list of host authentications
      uri:
        url: "https://{{ inventory_hostname }}/api/hosts/?filter[]=name={{ hostvars[item].rhv_host_name }}&expand=resources&attributes=authentications"
        user: "{{ miq_app_username }}"
        password: "{{ miq_app_password }}"
        method: GET
        validate_certs: no
      register: host_json
      until: host_json.json.subcount == 1
      retries: 30
      delay: 60

    - set_fact:
        query: "resources[?name=='{{ hostvars[item].rhv_host_name }}'].id"

    - name: Extracting host id from JSON
      set_fact:
        host_id: "{{ host_json.json | json_query(query) | first }}"

    - name: Add authentication for the host
      uri:
        url: "https://{{ inventory_hostname }}/api/hosts/{{ host_id }}/"
        user: "{{ miq_app_username }}"
        password: "{{ miq_app_password }}"
        method: POST
        validate_certs: no
        body_format: json
        body:
          action: edit
          resource:
            credentials:
              auth_type: default
              userid: root
              password: "{{ hostvars[item].root_password }}"

    - name: Remove conversion host tags if exist
      uri:
        url: "https://{{ inventory_hostname }}/api/hosts/{{ host_id }}/tags"
        user: "{{ miq_app_username }}"
        password: "{{ miq_app_password }}"
        method: POST
        validate_certs: no
        body_format: json
        body:
          action: unassign
          resources:
            - category: "v2v_transformation_host"
              name: "true"
            - category: "v2v_transformation_method"
              name: "vddk"
            - category: "v2v_transformation_method"
              name: "ssh"

    - name: Tag as conversion host
      uri:
        url: "https://{{ inventory_hostname }}/api/hosts/{{ host_id }}/tags"
        user: "{{ miq_app_username }}"
        password: "{{ miq_app_password }}"
        method: POST
        validate_certs: no
        body_format: json
        body:
          action: assign
          resources:
            - category: "v2v_transformation_host"
              name: "true"
            - category: "v2v_transformation_method"
              name: "vddk"
  tags:
    - miq_config_ovirt_conversion_hosts
