---

- name: Delete CFME logs
  script: roles/v2v.ci/files/del_logs.sh

- name: Start collecting CFME logs
  script: roles/v2v.ci/files/cfme_start_log.sh "v2v_test"

- name: Add Conversion hosts
  add_host:
    name: "{{ item }}"
    ansible_user: root
    ansible_ssh_pass: "{{ hostvars[item].root_password }}"
    ansible_pipelining: true
  with_items:
    -  "{{ groups['ovirt_conversion_hosts'] }}"

- name: Delete Conversion hosts logs
  delegate_to: "{{ item }}"
  script: roles/v2v.ci/files/del_logs.sh
  with_items:
    -  "{{ groups['ovirt_conversion_hosts'] }}"

- name: Start Collecting Conversion hosts logs
  delegate_to: "{{ item }}"
  script: roles/v2v.ci/files/conv_host_start_log.sh "v2v_test"
  with_items:
    -  "{{ groups['ovirt_conversion_hosts'] }}"
      
