---

# Add data iSCSI storage domain:
- name: Add data iSCSI storage domain
  ovirt_storage_domain:
    auth:
      username: "{{ v2v_ci_rhv_user }}"
      password: "{{ v2v_ci_rhv_password }}"
      hostname: "{{ v2v_ci_rhv_hostname }}"
      insecure: yes
    name: data_iscsi_domain
    host: "{{ groups['ovirt_conversion_hosts'][0] }}"
    data_center: "{{ data_center_name }}"
    iscsi:
      target: "{{ iscsi_target_wwn }}"
      lun_id:
       - "{{ '3' + create_lun_map_result['lun_naa_id'] }}"
      address: "{{ iscsi_target_ip }}"
    discard_after_delete: True