---
#- block:
#    - name: Set parameters
#      set_fact:
#        lineSearched : 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+VjThdZR0QfUCLtU/pIHsrOm5l7YOQ2t5SuWJuia8HWwsL2P2ghunQmQNOwtLVaj5Yge7w1uGMUBIxrwg8vjJ0gqub7eecN+6aCijJaC88+0R17b6r49CKwd3Tspl9ZcZ1Ou8esoBtzwaEvCupuw/UE5pnTnNbiUaV8y7FQChNssIiNnyE6BfRUJJsBw2R2/VdIwfISVdNWjdUFlMjeQuaJLSNTN/FTKs1UVrJCedRX3lZb8OEhtzAaREsh86Y+UmR5/2r1DnLU2pmaua99vETiNi1NJ/OhpWMmG1oFOz5AHXnndt/N7/X4/ogMoMWxBRi+jwJCBR53NXxX9nEUUb root@localhost.localdomain'
#
#    - name: Add SSH vmware ssh public key to VMware host
#      delegate_to: "{{ item }}"
#      lineinfile:
#        state: present
#        dest: /etc/ssh/keys-root/authorized_keys
#        regexp: "^{{ lineSearched }}"
#        line: "{{ lineSearched }}"
#      with_items:
#        -  "{{ groups['vmware_esx_hosts'] }}"
#  when: "{{ vmware_ssh_private_key }}" != null

- block:
  - name: Set parameters
    set_fact:
      lineSearched : 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+VjThdZR0QfUCLtU/pIHsrOm5l7YOQ2t5SuWJuia8HWwsL2P2ghunQmQNOwtLVaj5Yge7w1uGMUBIxrwg8vjJ0gqub7eecN+6aCijJaC88+0R17b6r49CKwd3Tspl9ZcZ1Ou8esoBtzwaEvCupuw/UE5pnTnNbiUaV8y7FQChNssIiNnyE6BfRUJJsBw2R2/VdIwfISVdNWjdUFlMjeQuaJLSNTN/FTKs1UVrJCedRX3lZb8OEhtzAaREsh86Y+UmR5/2r1DnLU2pmaua99vETiNi1NJ/OhpWMmG1oFOz5AHXnndt/N7/X4/ogMoMWxBRi+jwJCBR53NXxX9nEUUb root@localhost.localdomain'

  - name: Add SSH vmware ssh public key to VMware host
    delegate_to: "{{ item }}"
    become: yes
    become_user: root
    lineinfile:
      state: present
      dest: /etc/ssh/keys-root/authorized_keys
      regexp: "^{{ lineSearched }}"
      line: "{{ lineSearched }}"
    with_items:
      -  "{{ groups['vmware_esx_hosts'] }}"
  when: false

