---
- block:
  - block:
    - name: Add VMware hosts
      add_host:
        name: "{{ item }}"
        ansible_user: root
        ansible_ssh_pass: "{{ hostvars[item].root_password }}"
        ansible_pipelining: true
      with_items:
        -  "{{ groups['vmware_esx_hosts'] }}"

    - name: Add new public key to remote authorized_keys file
      delegate_to: "{{ item }}"
      authorized_key:
        key: "{{ vmware_ssh_public_key }}"
        user:  "{{ ansible_ssh_user }}"
        state: present
        exclusive: no
        path: /etc/ssh/keys-root/authorized_keys
      with_items:
        -  "{{ groups['vmware_esx_hosts'] }}"
    # Run this block only in case of ssh transport method is used:
    when: vmware_ssh_private_key is not none
  tags:
    - vmware_hosts_set_public_key